name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies and Build Angular
        run: |
          cd $GITHUB_WORKSPACE
          if [ -f "package.json" ]; then
            npm install
            npm run build
          elif [ -d "tutorial" ]; then
            cd tutorial && npm install && npm run build
          else
            cd * && if [ -f "package.json" ]; then npm install && npm run build; fi
          fi

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'frontend-tutorial-ekfkbkcegabaardf'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './dist/tutorial/browser'
